
name: Release Drafter

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          config-name: release-drafter.yml
#        if: github.event.review.state == 'approved'
